"""mql5-cloud-optimize — generate a tester.ini for MetaQuotes Cloud Network.

the kit spec §13 — Optimization=2 (Cloud) is gated by mode:

- PERSONAL:   REJECT — cloud time costs money, personal mode is local-only
- TEAM:       allowed; default budget cap 5 USD / pass
- ENTERPRISE: allowed; required budget cap, no upper limit

The script estimates cost using MetaQuotes' published rate
(0.001 USD per agent-second) × ``passes`` × ``period_seconds_per_pass``
and emits a tester.ini text plus a JSON cost report.

It never *runs* the optimization (that requires a paid Cloud Network
account); this is a planner + tester.ini generator only.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

Mode = Literal["personal", "team", "enterprise"]
MODE_DEFAULTS = {
    "personal":   {"allowed": False, "default_budget_usd": 0.0},
    "team":       {"allowed": True,  "default_budget_usd": 5.0},
    "enterprise": {"allowed": True,  "default_budget_usd": 50.0},
}

# Source: docs.mql5.com — pricing 0.001 USD per agent-second (2024-10).
CLOUD_RATE_USD_PER_SEC = 0.001

# Source: docs.mql5.com Strategy Tester reference. ``OptimizationCriterion`` is
# an enum, not a pass count.
OPTIMIZATION_CRITERIA = {
    0: "Balance max",
    1: "Profit Factor max",
    2: "Expected Payoff max",
    3: "Drawdown min",
    4: "Recovery Factor max",
    5: "Sharpe Ratio max",
    6: "Custom max (OnTester)",
}
DEFAULT_OPTIMIZATION_CRITERION = 0  # Balance max


@dataclass
class CostReport:
    ok: bool
    mode: str
    budget_usd: float
    estimated_cost_usd: float
    estimated_seconds: int
    passes: int
    error: str = ""

    def as_json(self) -> str:
        return json.dumps(self.__dict__, indent=2)


def estimate(passes: int, seconds_per_pass: int) -> tuple[int, float]:
    total = passes * seconds_per_pass
    return total, total * CLOUD_RATE_USD_PER_SEC


def plan(
    mode: Mode, passes: int, seconds_per_pass: int,
    budget_usd: float | None = None,
) -> CostReport:
    defaults = MODE_DEFAULTS[mode]
    if not defaults["allowed"]:
        return CostReport(
            ok=False, mode=mode, budget_usd=0.0, estimated_cost_usd=0.0,
            estimated_seconds=0, passes=passes,
            error="Cloud Network optimization is rejected in PERSONAL mode",
        )
    budget = budget_usd if budget_usd is not None else defaults["default_budget_usd"]
    seconds, cost = estimate(passes, seconds_per_pass)
    if mode == "enterprise" and budget_usd is None:
        return CostReport(
            ok=False, mode=mode, budget_usd=0.0, estimated_cost_usd=cost,
            estimated_seconds=seconds, passes=passes,
            error="ENTERPRISE mode requires explicit --budget-usd",
        )
    if cost > budget:
        return CostReport(
            ok=False, mode=mode, budget_usd=budget, estimated_cost_usd=cost,
            estimated_seconds=seconds, passes=passes,
            error=f"estimated cost {cost:.2f} > budget {budget:.2f}",
        )
    return CostReport(
        ok=True, mode=mode, budget_usd=budget, estimated_cost_usd=cost,
        estimated_seconds=seconds, passes=passes,
    )


def write_tester_ini(
    out_path: Path, ea: str, symbol: str, period: str, passes: int,
    optimization_criterion: int = DEFAULT_OPTIMIZATION_CRITERION,
) -> None:
    """Generate a tester.ini for Cloud Network optimization.

    ``optimization_criterion`` is a MetaTrader 5 enum (0..6) selecting which
    metric the optimizer maximises. See ``OPTIMIZATION_CRITERIA`` for the
    label of each integer. ``passes`` is recorded in a leading comment so the
    operator can see what the cost plan was based on, but it is **not** a
    standard tester.ini key.
    """
    if optimization_criterion not in OPTIMIZATION_CRITERIA:
        raise ValueError(
            f"optimization_criterion must be one of {sorted(OPTIMIZATION_CRITERIA)}, "
            f"got {optimization_criterion}",
        )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    text = (
        f"; Generated by mql5-cloud-optimize. Planned passes: {passes}.\n"
        "[Tester]\n"
        f"Expert={ea}\n"
        f"Symbol={symbol}\n"
        f"Period={period}\n"
        "Optimization=2\n"           # 2 = Cloud Network
        f"OptimizationCriterion={optimization_criterion}\n"
        "Visual=0\n"
    )
    out_path.write_text(text, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="mql5-cloud-optimize")
    parser.add_argument("ea", help="EA name (no path, no extension)")
    parser.add_argument("--mode", choices=list(MODE_DEFAULTS), default="personal")
    parser.add_argument("--symbol", default="EURUSD")
    parser.add_argument("--period", default="H1")
    parser.add_argument("--passes", type=int, default=1000)
    parser.add_argument("--seconds-per-pass", type=int, default=60)
    parser.add_argument("--budget-usd", type=float, default=None)
    parser.add_argument("--optimization-criterion", type=int,
                        default=DEFAULT_OPTIMIZATION_CRITERION,
                        choices=sorted(OPTIMIZATION_CRITERIA),
                        help="MT5 optimizer criterion enum (0=Balance max, "
                             "1=PF max, 2=Payoff max, 3=DD min, 4=RF max, "
                             "5=Sharpe max, 6=Custom)")
    parser.add_argument("--output-ini", default=None,
                        help="If set, write tester.ini to this path on success")
    args = parser.parse_args(argv)

    rep = plan(args.mode, args.passes, args.seconds_per_pass, args.budget_usd)
    print(rep.as_json())
    if rep.ok and args.output_ini:
        write_tester_ini(
            Path(args.output_ini), ea=args.ea, symbol=args.symbol,
            period=args.period, passes=args.passes,
            optimization_criterion=args.optimization_criterion,
        )
    return 0 if rep.ok else 1


if __name__ == "__main__":
    sys.exit(main())
