"""mql5-deploy-vps — gate deploy + emit MIGRATE-VPS.md guide.

Runs `trader_check` (must be >= 15/17 PASS) then writes a
``MIGRATE-VPS.md`` file at the chosen output path describing the steps
to migrate the EA to MetaQuotes VPS.

This module does NOT itself contact any VPS — it produces the runbook
the human EA dev will execute. the kit spec §13.

CLI:
    python -m vibecodekit_mql5.deploy_vps <ea.mq5> [--out MIGRATE-VPS.md]

Exit codes:
    0 — gate passed, guide written
    1 — gate failed (Trader-17 didn't reach threshold)
    2 — invocation error
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from vibecodekit_mql5 import trader_check


_TEMPLATE = """\
# MIGRATE-VPS.md — auto-generated by mql5-deploy-vps

**EA:** `{ea}`
**Trader-17 summary:** {summary}
**Verdict (personal mode):** {verdict}

## Pre-flight (do on your local MetaTrader 5 terminal)

1. Compile the EA in MetaEditor and verify `Result: 0 errors, 0 warnings`.
2. Run a 90-day backtest on at least the primary `Symbol`.
3. Run `mql5-multibroker` against your 3 demo broker accounts; stability
   tolerance must report `PASS`.

## VPS migration (MetaQuotes Virtual Hosting)

1. Right-click the chart with the EA → **Register a Virtual Server**.
2. Choose **Migration: Experts & indicators**, plus **Migrate the chart
   templates and tester cache**.
3. Wait for the green checkmark "Migrated successfully" in the *Journal*
   tab of *VPS* in Navigator.
4. Open the VPS log: confirm the EA's `OnInit` printed `[PipNorm]` with
   the expected `digits`/`point`/`pip` triple for the live symbol.

## Rollback

- Stop the VPS subscription, the local chart resumes after re-attach.
- Keep the original `.set` file at `Sets/default.set` for re-deploy.

## Trader-17 detail

{detail_lines}
"""


def render_guide(ea: Path, result: dict[str, str]) -> str:
    summary = result.get("_summary", "")
    pass_count = sum(1 for k, v in result.items() if not k.startswith("_") and v == "PASS")
    verdict_str = "PASS (>=15/17)" if pass_count >= 15 else "FAIL (<15/17)"
    detail_lines = "\n".join(
        f"- {k}: {v}" for k, v in result.items() if not k.startswith("_")
    )
    return _TEMPLATE.format(ea=ea, summary=summary,
                            verdict=verdict_str, detail_lines=detail_lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="mql5-deploy-vps", description=__doc__.splitlines()[0])
    p.add_argument("ea")
    p.add_argument("--out", default="MIGRATE-VPS.md")
    p.add_argument("--mode", choices=["personal", "enterprise"], default="personal")
    args = p.parse_args(argv)

    ea_path = Path(args.ea)
    if not ea_path.exists():
        print(f"[deploy_vps] EA not found: {ea_path}", file=sys.stderr)
        return 2

    from .mq5_io import read_mq5_text

    text = read_mq5_text(ea_path, errors="replace")
    result = trader_check.evaluate(text)
    ok = trader_check.verdict(result, mode=args.mode)
    Path(args.out).write_text(render_guide(ea_path, result), encoding="utf-8")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
