"""mql5-refine-tip -- auto-generate a TIP from a failing VERIFY.

When verify is NOT release-eligible, the operator should not have to
hand-author the remediation TIP. This reads the evidence manifest summary
and emits a concrete, prioritised TIP: one actionable item per failing or
missing check, mapped back to the command that produces the evidence.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from ._agent_io import Envelope, add_gate_report_flag, add_json_flag, maybe_emit
from .verify_evidence import resolve_manifest

TOOL = "mql5-refine-tip"

# Failing check -> (why it matters, command that produces the evidence).
_REMEDIES: dict[str, tuple[str, str]] = {
    "command_ok": ("The build command itself errored.", "re-run mql5-build and fix reported errors"),
    "compile_ok": ("No verified compile evidence.", "mql5-compile (real MetaEditor / remote worker)"),
    "gate_ok": ("Permission layers did not pass.", "mql5-permission-layer5 / mql5-doctor --soft"),
    "backtest_ok": ("No verified backtest evidence.", "mql5-backtest (real MT5 Strategy Tester / remote worker)"),
    "evidence_ok": ("Evidence manifest missing or empty.", "ensure evidence/ has hashed artefacts"),
}


def auto_tip(manifest: dict[str, Any]) -> tuple[str, list[str]]:
    """Return (markdown, failing_checks)."""
    summary = manifest.get("summary", {})
    eligible = bool(manifest.get("release_eligible") or summary.get("release_eligible"))
    failing = [k for k in _REMEDIES if k in summary and not summary.get(k)]
    skipped = summary.get("skipped_stages") or []
    unsafe = summary.get("unsafe_flags_used") or []

    lines = [
        "# TIP (auto-generated from VERIFY)",
        "",
        f"- Source verdict: {'release-eligible' if eligible else 'NOT release-eligible'}",
        f"- Failing checks: {len(failing)}",
        "",
        "## Prioritised actions",
    ]
    if not failing and not skipped and not unsafe:
        lines.append("- No failing checks detected. If verify still blocks, attach measured evidence.")
    n = 1
    for key in failing:
        why, cmd = _REMEDIES[key]
        lines.append(f"{n}. **{key}** -- {why}")
        lines.append(f"   - Action: {cmd}")
        n += 1
    for stage in skipped:
        lines.append(f"{n}. **skipped:{stage}** -- a required stage was skipped; re-run it without skip flags.")
        n += 1
    for flag in unsafe:
        lines.append(f"{n}. **unsafe:{flag}** -- remove the unsafe flag and re-run the gate honestly.")
        n += 1

    lines += [
        "",
        "## Refine envelope",
        "- Re-classify the fix with `mql5-refine --diff <patch>` (tweak / patch / rework).",
        "- `rework` requires the full 8-step methodology + matrix re-run.",
        "",
        "> Generated by `mql5-refine-tip`. This TIP does not assert PASS; it lists",
        "> what must be remediated before re-verifying.",
        "",
    ]
    return "\n".join(lines), failing


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog=TOOL, description="Auto-generate a remediation TIP from a failing VERIFY.")
    ap.add_argument("--evidence", type=Path, required=True,
                    help="Evidence dir, build out dir, or manifest.json.")
    ap.add_argument("--out", type=Path, default=None, help="Write the TIP markdown here.")
    add_json_flag(ap)
    add_gate_report_flag(ap)
    args = ap.parse_args(argv)

    mpath = resolve_manifest(args.evidence)
    if not mpath.is_file():
        sys.stderr.write(f"error: evidence manifest not found: {mpath}\n")
        return 2
    manifest = json.loads(mpath.read_text(encoding="utf-8"))
    md, failing = auto_tip(manifest)
    if args.out is not None:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(md, encoding="utf-8")
    if not args.emit_json:
        sys.stdout.write(md if args.out is None else f"wrote {args.out}\n")

    env = Envelope(
        tool=TOOL, ok=True, exit_code=0,
        summary=f"refine TIP: {len(failing)} failing check(s)",
        data={"failing_checks": failing, "manifest": str(mpath),
              "out": str(args.out) if args.out else None},
        evidence=[str(mpath)],
    )
    maybe_emit(args, env)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
