// digits-tested: 5,4,3,2
#pragma once
#include "../Config.mqh"
class CVCKEntryEngine
  {
private:
 string m_symbol; ENUM_TIMEFRAMES m_tf; int h_rsi,h_cci,h_stoch,h_fast,h_slow,h_bands,h_macd,h_atr,h_supertrend,h_utbot,h_momentum,h_ichimoku,h_external;
 bool Value(const int h,const int b,const int shift,double &out){double v[];ArrayResize(v,1);if(h==INVALID_HANDLE||BarsCalculated(h)<=shift||CopyBuffer(h,b,shift,1,v)!=1)return false;out=v[0];return MathIsValidNumber(out);}
 bool Rates(const int shift,const int count,MqlRates &r[]){ArrayResize(r,count);ArraySetAsSeries(r,true);return CopyRates(m_symbol,m_tf,shift,count,r)==count;}
 double Pip(){int d=(int)SymbolInfoInteger(m_symbol,SYMBOL_DIGITS);double p=SymbolInfoDouble(m_symbol,SYMBOL_POINT);return(d==3||d==5)?p*10.0:p;}
 double Highest(const MqlRates &r[],const int start,const int count){double x=-DBL_MAX;for(int i=start;i<start+count;i++)x=MathMax(x,r[i].high);return x;}
 double Lowest(const MqlRates &r[],const int start,const int count){double x=DBL_MAX;for(int i=start;i<start+count;i++)x=MathMin(x,r[i].low);return x;}
 int CandleColor(){MqlRates r[];if(!Rates(1,1,r))return 0;return r[0].close>r[0].open?1:(r[0].close<r[0].open?-1:0);}
 int Pinbar(){MqlRates r[];if(!Rates(1,1,r))return 0;double body=MathMax(MathAbs(r[0].close-r[0].open),_Point),up=r[0].high-MathMax(r[0].open,r[0].close),dn=MathMin(r[0].open,r[0].close)-r[0].low,range=(r[0].high-r[0].low);if(range<InpMinCandlePips*Pip())return 0;if(dn>=InpPinbarWickRatio*body&&dn>=InpPinbarOppositeRatio*up)return 1;if(up>=InpPinbarWickRatio*body&&up>=InpPinbarOppositeRatio*dn)return -1;return 0;}
 int Engulfing(){MqlRates r[];if(!Rates(1,2,r))return 0;bool bull=InpEngulfFullWick?(r[0].low<=r[1].low&&r[0].high>=r[1].high):(r[1].close<r[1].open&&r[0].close>r[0].open&&r[0].open<=r[1].close&&r[0].close>=r[1].open);bool bear=InpEngulfFullWick?(r[0].high>=r[1].high&&r[0].low<=r[1].low&&r[0].close<r[0].open):(r[1].close>r[1].open&&r[0].close<r[0].open&&r[0].open>=r[1].close&&r[0].close<=r[1].open);return bull?1:(bear?-1:0);}
 int Structure(const int lookback,const bool against){MqlRates r[];if(!Rates(1,lookback+2,r))return 0;double hi=Highest(r,1,lookback),lo=Lowest(r,1,lookback);int d=r[0].close>hi?1:(r[0].close<lo?-1:0);return against?-d:d;}
public:
 CVCKEntryEngine():h_rsi(INVALID_HANDLE),h_cci(INVALID_HANDLE),h_stoch(INVALID_HANDLE),h_fast(INVALID_HANDLE),h_slow(INVALID_HANDLE),h_bands(INVALID_HANDLE),h_macd(INVALID_HANDLE),h_atr(INVALID_HANDLE),h_supertrend(INVALID_HANDLE),h_utbot(INVALID_HANDLE),h_momentum(INVALID_HANDLE),h_ichimoku(INVALID_HANDLE),h_external(INVALID_HANDLE){}
 bool Init(const string symbol,const ENUM_TIMEFRAMES tf){m_symbol=symbol;m_tf=tf;h_rsi=iRSI(symbol,tf,InpRSIPeriod,PRICE_CLOSE);h_cci=iCCI(symbol,tf,InpCCIPeriod,PRICE_CLOSE);h_stoch=iStochastic(symbol,tf,InpStochK,InpStochD,InpStochSlowing,MODE_SMA,STO_LOWHIGH);h_fast=iMA(symbol,tf,InpEMAFast,0,MODE_EMA,PRICE_CLOSE);h_slow=iMA(symbol,tf,InpEMASlow,0,MODE_EMA,PRICE_CLOSE);h_bands=iBands(symbol,tf,InpBBPeriod,0,InpBBDeviation,PRICE_CLOSE);h_macd=iMACD(symbol,tf,12,26,9,PRICE_CLOSE);h_atr=iATR(symbol,tf,InpATRPeriod);h_supertrend=iATR(symbol,tf,InpSupertrendPeriod);h_utbot=iATR(symbol,tf,InpUTBotPeriod);h_momentum=iMomentum(symbol,tf,InpMomentumPeriod,PRICE_CLOSE);h_ichimoku=iIchimoku(symbol,tf,InpIchimokuTenkan,InpIchimokuKijun,InpIchimokuSenkou);if(StringLen(InpExternalIndicator)>0)h_external=iCustom(symbol,tf,InpExternalIndicator);return ReadyHandles();}
 void Release(){int a[]={h_rsi,h_cci,h_stoch,h_fast,h_slow,h_bands,h_macd,h_atr,h_supertrend,h_utbot,h_momentum,h_ichimoku,h_external};for(int i=0;i<ArraySize(a);i++)if(a[i]!=INVALID_HANDLE)IndicatorRelease(a[i]);}
 bool ReadyHandles(){int a[]={h_rsi,h_cci,h_stoch,h_fast,h_slow,h_bands,h_macd,h_atr,h_supertrend,h_utbot,h_momentum,h_ichimoku};for(int i=0;i<ArraySize(a);i++)if(a[i]==INVALID_HANDLE)return false;return true;}
 bool EMAFilterAllow(const int direction){if(!InpUseEMAFilter&&InpEMAMaxPriceDistancePips<=0&&InpEMAMinSeparationPips<=0)return true;double fast,slow;MqlRates rate[];if(!Value(h_fast,0,1,fast)||!Value(h_slow,0,1,slow)||!Rates(0,1,rate))return false;if(InpUseEMAFilter&&direction>0&&fast<=slow)return false;if(InpUseEMAFilter&&direction<0&&fast>=slow)return false;double pip=Pip();if(InpEMAMaxPriceDistancePips>0&&MathAbs(rate[0].close-fast)/pip>InpEMAMaxPriceDistancePips)return false;if(InpEMAMinSeparationPips>0&&MathAbs(fast-slow)/pip<InpEMAMinSeparationPips)return false;return true;}
 bool MACDFilterAllow(const int direction){if(!InpUseMACDFilter)return true;double main,signal;if(!Value(h_macd,0,1,main)||!Value(h_macd,1,1,signal))return false;return direction>0?main>signal:main<signal;}
 bool RSIFilterAllow(const int direction){if(!InpUseRSIFilter)return true;double value;if(!Value(h_rsi,0,1,value))return false;return direction>0?value>=50:value<=50;}
 bool FiltersAllow(const int direction){return EMAFilterAllow(direction)&&MACDFilterAllow(direction)&&RSIFilterAllow(direction);}
 int SignalRSI(){double a;if(!Value(h_rsi,0,1,a))return 0;return a<=InpRSIOversold?1:(a>=InpRSIOverbought?-1:0);}
 int SignalRSIReversal(){double a,b;if(!Value(h_rsi,0,2,a)||!Value(h_rsi,0,1,b))return 0;return a<=InpRSIOversold&&b>InpRSIOversold?1:(a>=InpRSIOverbought&&b<InpRSIOverbought?-1:0);}
 int SignalCCIReversal(){double a,b;if(!Value(h_cci,0,2,a)||!Value(h_cci,0,1,b))return 0;return a<=InpCCIOversold&&b>InpCCIOversold?1:(a>=InpCCIOverbought&&b<InpCCIOverbought?-1:0);}
 int SignalStochastic(){double a,b,c,d;if(!Value(h_stoch,0,2,a)||!Value(h_stoch,1,2,b)||!Value(h_stoch,0,1,c)||!Value(h_stoch,1,1,d))return 0;if(a<=b&&c>d&&c<20)return 1;if(a>=b&&c<d&&c>80)return -1;return 0;}
 int SignalEMACross(){double a,b,c,d;if(!Value(h_fast,0,2,a)||!Value(h_slow,0,2,b)||!Value(h_fast,0,1,c)||!Value(h_slow,0,1,d))return 0;return a<=b&&c>d?1:(a>=b&&c<d?-1:0);}
 int SignalBands(){double lower_prev,lower_now,upper_prev,upper_now;MqlRates r[];if(!Value(h_bands,2,2,lower_prev)||!Value(h_bands,2,1,lower_now)||!Value(h_bands,1,2,upper_prev)||!Value(h_bands,1,1,upper_now)||!Rates(1,2,r))return 0;if(r[1].close<lower_prev&&r[0].close>lower_now)return 1;if(r[1].close>upper_prev&&r[0].close<upper_now)return -1;return 0;}
 int SignalMACD(){double a,b,c,d;if(!Value(h_macd,0,2,a)||!Value(h_macd,1,2,b)||!Value(h_macd,0,1,c)||!Value(h_macd,1,1,d))return 0;return a<=b&&c>d?1:(a>=b&&c<d?-1:0);}
 int SignalMomentum(){double a;if(!Value(h_momentum,0,1,a))return 0;return a>=InpMomentumBuyLevel?1:(a<=InpMomentumSellLevel?-1:0);}
 int SignalATRBreak(){double atr;MqlRates r[];if(!Value(h_atr,0,1,atr)||!Rates(1,2,r))return 0;if(r[0].close>r[1].high+InpATRBreakMultiplier*atr)return 1;if(r[0].close<r[1].low-InpATRBreakMultiplier*atr)return -1;return 0;}
 int SignalSupertrend(){double atr;MqlRates r[];if(!Value(h_supertrend,0,1,atr)||!Rates(1,2,r))return 0;double mid=(r[0].high+r[0].low)/2;return r[0].close>mid-InpSupertrendMultiplier*atr?1:-1;}
 int SignalUTBot(){double atr;MqlRates r[];if(!Value(h_utbot,0,1,atr)||!Rates(1,2,r))return 0;if(r[0].close>r[1].close+InpUTBotSensitivity*atr)return 1;if(r[0].close<r[1].close-InpUTBotSensitivity*atr)return -1;return 0;}
 int SignalIchimoku(){double a,b;MqlRates r[];if(!Value(h_ichimoku,2,1,a)||!Value(h_ichimoku,3,1,b)||!Rates(1,1,r))return 0;double top=MathMax(a,b),bottom=MathMin(a,b);return r[0].close>top?1:(r[0].close<bottom?-1:0);}
 int SignalExternal(){double a,b;if(h_external==INVALID_HANDLE)return 0;if(Value(h_external,InpExternalBuyBuffer,1,a)&&a!=0&&a!=EMPTY_VALUE)return 1;if(Value(h_external,InpExternalSellBuffer,1,b)&&b!=0&&b!=EMPTY_VALUE)return -1;return 0;}
 int OscillatorDirection(){switch(InpSignalMode){case VCK_SIGNAL_RSI:return SignalRSI();case VCK_SIGNAL_RSI_REVERSAL:return SignalRSIReversal();case VCK_SIGNAL_CCI_REVERSAL:return SignalCCIReversal();case VCK_SIGNAL_STOCH_REVERSAL:return SignalStochastic();default:return 0;}}
 int ClassicDirection(){switch(InpSignalMode){case VCK_SIGNAL_EMA_CROSS:return SignalEMACross();case VCK_SIGNAL_BB_REVERSION:return SignalBands();case VCK_SIGNAL_PINBAR:return Pinbar();case VCK_SIGNAL_ENGULFING:return Engulfing();case VCK_SIGNAL_PINBAR_ENGULFING:{int x=Pinbar();return x!=0?x:Engulfing();}case VCK_SIGNAL_MACD_CROSS:return SignalMACD();default:return 0;}}
 int TrendDirection(){switch(InpSignalMode){case VCK_SIGNAL_MOMENTUM:return SignalMomentum();case VCK_SIGNAL_ATR_BREAKOUT:return SignalATRBreak();case VCK_SIGNAL_SUPERTREND:return SignalSupertrend();case VCK_SIGNAL_UTBOT:return SignalUTBot();case VCK_SIGNAL_ICHIMOKU_BREAK:return SignalIchimoku();default:return 0;}}
 int SMCDirection(){switch(InpSignalMode){case VCK_SIGNAL_SMC_ALL_WITH:return Structure(InpSMCSwingLookback,false);case VCK_SIGNAL_SMC_ALL_AGAINST:return Structure(InpSMCSwingLookback,true);case VCK_SIGNAL_SMC_INTERNAL_WITH:return Structure(InpSMCInternalLookback,false);case VCK_SIGNAL_SMC_INTERNAL_AGAINST:return Structure(InpSMCInternalLookback,true);case VCK_SIGNAL_SMC_SWING_WITH:return Structure(InpSMCSwingLookback,false);case VCK_SIGNAL_SMC_SWING_AGAINST:return Structure(InpSMCSwingLookback,true);default:return 0;}}
 int SpecialDirection(){switch(InpSignalMode){case VCK_SIGNAL_CANDLE_COLOR:return CandleColor();case VCK_SIGNAL_NO_CONDITION:return InpUnconditionalDirection>=0?1:-1;case VCK_SIGNAL_RANDOM:return MathRand()%2==0?1:-1;case VCK_SIGNAL_EXTERNAL:return SignalExternal();default:return 0;}}
 int Direction(){int mode=(int)InpSignalMode;if(mode>=VCK_SIGNAL_RSI&&mode<=VCK_SIGNAL_STOCH_REVERSAL)return OscillatorDirection();if(mode>=VCK_SIGNAL_EMA_CROSS&&mode<=VCK_SIGNAL_MACD_CROSS)return ClassicDirection();if(mode>=VCK_SIGNAL_MOMENTUM&&mode<=VCK_SIGNAL_ICHIMOKU_BREAK)return TrendDirection();if(mode>=VCK_SIGNAL_SMC_ALL_WITH&&mode<=VCK_SIGNAL_SMC_SWING_AGAINST)return SMCDirection();return SpecialDirection();}
  };
